<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>AimPointGenerator</RootNamespace>
    <AssemblyName>AimPointGenerator</AssemblyName>
  </PropertyGroup>

</Project>
